### ISSUE TITLE
'Unhandled rejection SyntaxError' on 'deploy -f'

### ISSUE THREAD

**Issue by mattwalter91** [mdyd-dev/marketplace-kit#110]
## Expected behavior 
The error should be more meaningful. I believe it's because I had a customization that needs clearing before I can deploy, and I'll confirm that in a comment after this.

## Actual behavior

`
Unhandled rejection SyntaxError: Unexpected token : in JSON at position 1
    at JSON.parse (<anonymous>)
    at gateway.getStatus.then.response (C:\Users\mattu\AppData\Roaming\npm\node_modules\@platform-os\marketplace-kit\marketplace-kit-push.js:58:35)
    at tryCatcher (C:\Users\mattu\AppData\Roaming\npm\node_modules\@platform-os\marketplace-kit\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\mattu\AppData\Roaming\npm\node_modules\@platform-os\marketplace-kit\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\mattu\AppData\Roaming\npm\node_modules\@platform-os\marketplace-kit\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\mattu\AppData\Roaming\npm\node_modules\@platform-os\marketplace-kit\node_modules\bluebird\js\release\promise.js:614:10)    at Promise._settlePromises (C:\Users\mattu\AppData\Roaming\npm\node_modules\@platform-os\marketplace-kit\node_modules\bluebird\js\release\promise.js:694:18)    at _drainQueueStep (C:\Users\mattu\AppData\Roaming\npm\node_modules\@platform-os\marketplace-kit\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (C:\Users\mattu\AppData\Roaming\npm\node_modules\@platform-os\marketplace-kit\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\mattu\AppData\Roaming\npm\node_modules\@platform-os\marketplace-kit\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues (C:\Users\mattu\AppData\Roaming\npm\node_modules\@platform-os\marketplace-kit\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
`

## Steps to reproduce the problem
`marketplace-kit deploy -f mw-namespace`

### Marketplace Kit
v2.6.6

### NodeJs
v8.11.2

### Operating System
Windows 10

**Comment by mattwalter91** [comment]
Deploying works after I clear all customizations:

`mutation{ customizations_delete_all(all_custom_model_types:true) }`

The error log used to tell you that is was this issue, and to run the above command. Seems there's a `:` in the response now that's causing issues when you `JSON.parse`
